on: [push]

name: Push
jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy --tests -- -Dwarnings

      - name: Check Formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check

      - name: Unit Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release

      - name: Check Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --bins --release
