on: [push]

name: Push
jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy

      - name: Check Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --bins --release
